kind: pipeline
name: default
type: kubernetes

steps:
  - name: build
    image: texlive/texlive:latest
    commands:
      - apt-get update && apt-get -y install inkscape python3-pygments
      - latexmk -shell-escape -pdf resume.tex
